using System.Threading.Tasks;
using System.Linq;
using System.Xml.Linq;
using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Shapes;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------



namespace osu_Sync.My.Resources
{

	//Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
	//-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
	//Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
	//mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
	///<summary>
	///  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
	///</summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Microsoft.VisualBasic.HideModuleNameAttribute()]
	static internal class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		///<summary>
		///  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("osu_Sync.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		///<summary>
		///  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
		///  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Globalization.CultureInfo Culture {
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		///<summary>
		///  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
		///</summary>
		static internal System.Drawing.Icon nw520_osbl {
			get {
				object obj = ResourceManager.GetObject("nw520_osbl", resourceCulture);
				return (System.Drawing.Icon)obj;
			}
		}
	}
}
